# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main

pool: self-hosted

variables:
  buildConfiguration: Release
  projectDirectory: 'mslearn-tailspin-spacegame-web'


steps:
  - task: DotNetCoreCLI@2
    name: restore
    inputs:
      command: 'restore'
      projects: '$(Build.SourcesDirectory)/$(projectDirectory)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build $(buildConfiguration)'
    name: build
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      projects: '$(Build.SourcesDirectory)/$(projectDirectory)'