name: dotnet-buil-ci
on:
  push:
  repository_dispatch:
  workflow_dispatch:

env:
  dotnet-version: "6" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout
         uses: actions/checkout@v4.1.2
      -  name: Setup dotnet
         uses: actions/setup-dotnet@v4
         with:
            dotnet-version: env.dotnet-version
      - name: Restore project dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration release "**/*.csproj"
